name: maljrs-env
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pip
  - pip:
      - crewai>=0.28.0
      - crewai-tools>=0.2.6
      - langchain-ollama>=0.1.5
      - python-dotenv>=1.0.1
      - joblib>=1.4.2
      - scikit-learn>=1.5.1
